CREATE USER codegen WITH PASSWORD 'XXXXXX';

GRANT CONNECT ON DATABASE mydb TO codegen;
ALTER DEFAULT PRIVILEGES FOR USER codegen IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO codegen;
ALTER DEFAULT PRIVILEGES FOR USER codegen IN SCHEMA public GRANT USAGE ON SEQUENCES TO codegen;
ALTER DEFAULT PRIVILEGES FOR USER codegen IN SCHEMA public GRANT USAGE ON TYPES TO codegen;

GRANT USAGE ON SCHEMA public TO codegen;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO codegen;
